# ===============================
# IMPORTANT
# ===============================
spring.application.name=backend
app.cors.allowed-origins=http://localhost:3000
spring.profiles.active=dev

# ===============================
# DATABASE CONNECTION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5433/tipon
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===============================
# TOKEN
# ===============================
jwt.secret=qGmHsH4q3IF8l7hqXrv^OL3y0oQaXnSc
jwt.expiration-ms=86400000  